In [1]:
import pandas as pd

In [1]:
a=pd.read_csv('data/cars.csv')

NameError: name 'pd' is not defined

In [2]:
a

NameError: name 'a' is not defined

 () & () -->format remember

In [5]:

# LOGICAL AND OPERATOR
a.loc[ (a['Origin']=='US') & (a['Model']==70)]

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US
5,Ford Galaxie 500,15.0,8.0,429.0,198.0,4341,10.0,70,US
6,Chevrolet Impala,14.0,8.0,454.0,220.0,4354,9.0,70,US
7,Plymouth Fury iii,14.0,NaN,440.0,215.0,4312,8.5,70,US
8,Pontiac Catalina,14.0,8.0,455.0,225.0,4425,10.0,70,US
9,AMC Ambassador DPL,15.0,8.0,390.0,190.0,3850,8.5,70,US
11,Chevrolet Chevelle Concours (sw),0.0,8.0,350.0,NaN,4142,11.5,70,US
12,Ford Torino (sw),0.0,8.0,351.0,153.0,4034,11.0,70,US
13,Plymouth Satellite (sw),0.0,8.0,383.0,175.0,4166,10.5,70,US
14,AMC Rebel SST (sw),0.0,8.0,360.0,175.0,3850,11.0,70,US
15,Dodge Challenger SE,15.0,8.0,383.0,170.0,3563,10.0,70,US
16,Plymouth 'Cuda 340,14.0,8.0,340.0,160.0,3609,8.0,70,US
17,Ford Mustang Boss 302,0.0,8.0,302.0,140.0,3353,8.0,70,US
18,Chevrolet Monte Carlo,15.0,8.0,400.0,150.0,3761,9.5,70,US
19,Buick Estate Wagon (sw),14.0,8.0,455.0,225.0,3086,10.0,70,US
21,Plymouth Duster,22.0,6.0,198.0,95.0,2833,15.5,70,US
22,AMC Hornet,18.0,6.0,199.0,NaN,2774,15.5,70,US
23,Ford Maverick,21.0,6.0,200.0,85.0,2587,16.0,70,US
30,AMC Gremlin,21.0,6.0,199.0,90.0,2648,15.0,70,US
31,Ford F250,10.0,8.0,360.0,215.0,4615,14.0,70,US
32,Chevy C20,10.0,8.0,307.0,200.0,4376,15.0,70,US
33,Dodge D200,11.0,8.0,318.0,210.0,4382,13.5,70,US
34,Hi 1200D,9.0,8.0,304.0,193.0,4732,18.5,70,US

In [22]:
#LOGICAL OR OPERATOR
a.loc[ (a['Cylinders']==8.0) | (a['Model']==70)]

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US
...,...,...,...,...,...,...,...,...,...
298,Chevrolet Malibu Classic (sw),19.2,8.0,267.0,125.0,3605,15.0,79,US
299,Chrysler Lebaron Town @ Country (sw),18.5,8.0,360.0,150.0,3940,13.0,79,US
305,Cadillac Eldorado,23.0,8.0,350.0,125.0,3900,17.4,79,US
307,Oldsmobile Cutlass Salon Brougham,23.9,8.0,260.0,90.0,3420,22.2,79,US
372,Oldsmobile Cutlass LS,26.6,8.0,350.0,105.0,3725,19.0,81,US

In [30]:
# LOGICAL NOT OPERATOR
a.loc[~ (a['Origin']=='US') & ~ (a['Model']==70)]

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
35,Datsun PL510,27.0,4.0,97.0,88.0,2130,14.5,71,Japan
37,Toyota Corolla,25.0,4.0,113.0,95.0,2228,14.0,71,Japan
39,Volkswagen Super Beetle 117,0.0,4.0,97.0,48.0,1978,20.0,71,Europe
57,Opel 1900,28.0,4.0,116.0,90.0,2123,14.0,71,Europe
58,Peugeot 304,30.0,4.0,79.0,70.0,2074,19.5,71,Europe
...,...,...,...,...,...,...,...,...,...
391,Honda Civic,38.0,4.0,91.0,67.0,1965,15.0,82,Japan
392,Honda Civic (auto),32.0,4.0,91.0,67.0,1965,15.7,82,Japan
393,Datsun 310 GX,38.0,4.0,91.0,67.0,1995,16.2,82,Japan
398,Toyota Celica GT,32.0,4.0,144.0,96.0,2665,13.9,82,Japan
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe