In [1]:
import pandas as pd

In [2]:
a=pd.read_csv('data/cars.csv')
a

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
0,Chevrolet Chevelle Malibu,18.0,8.0,307.0,130.0,3504,12.0,70,US
1,Buick Skylark 320,15.0,8.0,350.0,165.0,3693,11.5,70,US
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
3,AMC Rebel SST,16.0,8.0,304.0,150.0,3433,12.0,70,US
4,Ford Torino,17.0,8.0,302.0,140.0,3449,10.5,70,US
...,...,...,...,...,...,...,...,...,...
401,Ford Mustang GL,27.0,4.0,140.0,86.0,2790,15.6,82,US
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
403,Dodge Rampage,32.0,4.0,135.0,84.0,2295,11.6,82,US
404,Ford Ranger,28.0,4.0,120.0,79.0,2625,18.6,82,US
405,Chevy S-10,31.0,4.0,119.0,82.0,2720,19.4,82,US

In [ ]:
a.sort_values(by=)

# sysntax : sort_values( by=column_name , asc=true|false , na_position= first|last)

In [18]:
a.sort_values(by='Car')

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
103,AMC Ambassador Brougham,13.0,8.0,360.0,175.0,3821,11.0,73,US
9,AMC Ambassador DPL,15.0,8.0,390.0,190.0,3850,8.5,70,US
73,AMC Ambassador SST,17.0,8.0,304.0,150.0,3672,11.5,72,US
264,AMC Concord,19.4,6.0,232.0,90.0,3210,17.2,78,US
322,AMC Concord,24.3,4.0,151.0,90.0,3003,20.1,80,US
...,...,...,...,...,...,...,...,...,...
83,Volvo 145e (sw),18.0,4.0,121.0,112.0,2933,14.5,72,Europe
186,Volvo 244DL,22.0,4.0,121.0,98.0,2945,14.5,75,Europe
214,Volvo 245,20.0,4.0,130.0,102.0,3150,15.7,76,Europe
282,Volvo 264gl,17.0,6.0,163.0,125.0,3140,13.6,78,Europe
368,Volvo Diesel,30.7,6.0,145.0,76.0,3160,19.6,81,Europe

In [20]:
a.sort_values(by='Cylinders',ascending=False)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
372,Oldsmobile Cutlass LS,26.6,8.0,350.0,105.0,3725,19.0,81,US
32,Chevy C20,10.0,8.0,307.0,200.0,4376,15.0,70,US
31,Ford F250,10.0,8.0,360.0,215.0,4615,14.0,70,US
19,Buick Estate Wagon (sw),14.0,8.0,455.0,225.0,3086,10.0,70,US
18,Chevrolet Monte Carlo,15.0,8.0,400.0,150.0,3761,9.5,70,US
...,...,...,...,...,...,...,...,...,...
341,Mazda RX-7 GS,23.7,3.0,70.0,100.0,2420,12.5,80,Japan
250,Mazda RX-4,21.5,3.0,80.0,110.0,2720,13.5,77,Japan
78,Mazda RX2 Coupe,19.0,3.0,70.0,97.0,2330,13.5,72,Japan
118,Mazda RX3,18.0,3.0,70.0,90.0,2124,13.5,73,Japan
7,Plymouth Fury iii,14.0,NaN,440.0,215.0,4312,8.5,70,US

In [21]:
a.sort_values(by='Acceleration',ascending=False,na_position='first')

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin
2,Plymouth Satellite,18.0,8.0,318.0,150.0,3436,NaN,70,US
306,Peugeot 504,27.2,4.0,141.0,71.0,3190,24.8,79,Europe
402,Volkswagen Pickup,44.0,4.0,97.0,52.0,2130,24.6,82,Europe
333,Volkswagen Dasher (diesel),43.4,4.0,90.0,48.0,2335,23.7,80,Europe
66,Volkswagen Type 3,23.0,4.0,97.0,54.0,2254,23.5,72,Europe
...,...,...,...,...,...,...,...,...,...
6,Chevrolet Impala,14.0,8.0,454.0,220.0,4354,9.0,70,US
9,AMC Ambassador DPL,15.0,8.0,390.0,190.0,3850,8.5,70,US
7,Plymouth Fury iii,14.0,NaN,440.0,215.0,4312,8.5,70,US
17,Ford Mustang Boss 302,0.0,8.0,302.0,140.0,3353,8.0,70,US
16,Plymouth 'Cuda 340,14.0,8.0,340.0,160.0,3609,8.0,70,US