In [46]:
import pandas as pd

In [ ]:
# DATA 1 = A
# DATA 2 = A
data1=pd.DataFrame([[1,11,21],[2,12,22],[3,13,23]],columns=['A','B','C'])
data2=pd.DataFrame([[1,11,21],[2,12,22],[3,13,23]],columns=['E','F','A'])

In [48]:
# LEFT-->(L), RIGHT-->(R), INNER-->(COMMON VALUES), OUTER-->(ALL COLUMN,NO VALUES NA)
qw,qe=(data1.align(data2,join='inner',axis=1))

In [49]:
qw

   A
0  1
1  2
2  3

In [50]:
qe

    A
0  21
1  22
2  23